# Generated by Django 4.2.7 on 2025-10-10 21:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(max_length=20, unique=True)),
                ('equipment_type', models.CharField(choices=[('forklift', 'Forklift'), ('crane', 'Crane'), ('loader', 'Loader')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='idle', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=50)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_type', models.CharField(choices=[('no_ppe', 'No PPE'), ('overspeed', 'Overspeed'), ('zone_breach', 'Restricted Zone Breach'), ('unsafe_operation', 'Unsafe Operation')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(max_length=20, unique=True)),
                ('license_plate', models.CharField(max_length=15)),
                ('driver_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('current_status', models.CharField(choices=[('gate_in', 'Gate In'), ('docked', 'Docked'), ('loading', 'Loading'), ('departed', 'Departed'), ('delayed', 'Delayed')], default='gate_in', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TruckEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('gate_in', 'Gate In'), ('docked', 'Docked'), ('loading_start', 'Loading Start'), ('loading_end', 'Loading End'), ('departed', 'Departed'), ('delay', 'Delay'), ('safety_alert', 'Safety Alert')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.truck')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night')], max_length=10)),
                ('total_trucks', models.IntegerField(default=0)),
                ('avg_turnaround_time', models.FloatField(default=0.0)),
                ('on_time_percentage', models.FloatField(default=0.0)),
                ('delay_percentage', models.FloatField(default=0.0)),
                ('dock_utilization', models.FloatField(default=0.0)),
                ('safety_violations', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'shift'],
                'unique_together': {('date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dock_id', models.CharField(max_length=10, unique=True)),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('utilization_rate', models.FloatField(default=0.0)),
                ('current_truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.truck')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('delay', 'Delay Alert'), ('safety', 'Safety Alert'), ('equipment', 'Equipment Alert'), ('congestion', 'Congestion Alert')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('related_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.equipment')),
                ('related_truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.truck')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
